name: JuiceShop Build CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install Deps
      working-directory: ${{ github.workspace }}
      run: npm install
    - name: Install Standard
      working-directory: ${{ github.workspace }}
      run: npm i -g standard@14
    - name: Angular CLI
      working-directory: ${{ github.workspace}}
      run: npm install -g @angular/cli > /dev/null
    - name: Install Frontend Deps
      working-directory: ./frontend
      run: npm install
    - name: Run lint
      working-directory: ${{ github.workspace }}
      run: npm run lint