name: JuiceShop Build CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install Deps
      run: npm install
    - name: Lint
      run: npm i -g standard@14 && cd frontend && npm install && cd .. && npm run lint
    - name: Test
      run: npm test