name: JuiceShop Build CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install Deps
      run: npm install
    - name: Lint
      run: |
        echo "installing standard"
        npm i -g standard@14
        echo "going into frontend"
        cd frontend
        echo "npm install frontend"
        npm install
        echo "back one dir"
        cd ..
        echo "run lint"
        npm run lint